database:
  # Partial support
  postgres:
    enabled: false
  mysql:
    enabled: true
    host: "host"
    user: "user"
    password: "password"
    db: "db"
  # Not supported yet
  duckdb:
    enabled: false
