database:
  # Partial support
  postgres:
    enabled: true
    host: "host"
    port: 5432
    database: "database"
    username: "user"
    password: "password"
  mysql:
    enabled: true
    host: "host"
    user: "user"
    password: "password"
    db: "db"
  # Not supported yet
  duckdb:
    enabled: false
    path: "path/to/duckdb"
